version: "3.9"
services:
  app:
    build: 
      context: app
      dockerfile: Dockerfile
    ports:
      - "5000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://fastapi:fastapi@db:5432/fastapi
    depends_on:
      - db
    command: uvicorn app:app --reload --host 0.0.0.0 --port 5000
    volumes:
      - ./app/:/app/
    
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx_config.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  postgres_data_prod: